# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('name_no', models.CharField(max_length=30)),
                ('name_jp', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('comment_en', models.TextField()),
                ('comment_no', models.TextField()),
                ('comment_jp', models.TextField()),
            ],
        ),
    ]
