# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20171030_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('pr', 'Preview'), ('na', 'Nature'), ('pe', 'People'), ('ur', 'Urban')], max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(help_text='Select date taken'),
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.ManyToManyField(help_text='Select tag for this picture', to='images.Tag'),
        ),
    ]
