# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20171030_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tag',
            new_name='tags',
        ),
    ]
